server:
  port: 8760
spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username:  root
    password:  admin
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/

#注册中心
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 3000
# 打印sql
logging:
  level:
    com.spring.cloud: debug
#扫描文件路径
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.spring.cloud.domain.entity
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  redis
#幂等配置
idempotent:
  jdbc:
    global-table: ods_biz_idempotent
school:
  name: 小伙子
  age: 12


