server:
  port: 8760
spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username:  root
    password:  admin
  redis:
    database: 5
    host: 122.51.171.126
    port: 6379 # Redis服务器连接端口
    password: ak402507979 # Redis服务器连接密码（默认为空）
  thymeleaf:
    prefix: classpath:/templates/
  rabbitmq:
      host: 122.51.171.126
      port: 5672
      username: user01
      password: ak402507979
      virtual-host: /

#注册中心
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 3000
# 打印sql
logging:
  level:
    com.spring.cloud: debug
#扫描文件路径
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.spring.cloud.domain.entity
#  configuration:
#    map-underscore-to-camel-case: true
#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  redis


