package com.spring.cloud.domain.entity;

import java.util.Date;

public class MsgLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.FROM_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.TO_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.CLIENT_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.MSG_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.CONTENT
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.SEND_FROM
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Byte sendFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.IS_DELETED
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.CREATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.CREATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.UPDATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.UPDATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_msg_log.RECORD_VERSION
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    private Integer recordVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.ID
     *
     * @return the value of tt_msg_log.ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.ID
     *
     * @param id the value for tt_msg_log.ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.FROM_USER_ID
     *
     * @return the value of tt_msg_log.FROM_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.FROM_USER_ID
     *
     * @param fromUserId the value for tt_msg_log.FROM_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.TO_USER_ID
     *
     * @return the value of tt_msg_log.TO_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.TO_USER_ID
     *
     * @param toUserId the value for tt_msg_log.TO_USER_ID
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.CLIENT_TYPE
     *
     * @return the value of tt_msg_log.CLIENT_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.CLIENT_TYPE
     *
     * @param clientType the value for tt_msg_log.CLIENT_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.MSG_TYPE
     *
     * @return the value of tt_msg_log.MSG_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.MSG_TYPE
     *
     * @param msgType the value for tt_msg_log.MSG_TYPE
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.CONTENT
     *
     * @return the value of tt_msg_log.CONTENT
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.CONTENT
     *
     * @param content the value for tt_msg_log.CONTENT
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.SEND_FROM
     *
     * @return the value of tt_msg_log.SEND_FROM
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Byte getSendFrom() {
        return sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.SEND_FROM
     *
     * @param sendFrom the value for tt_msg_log.SEND_FROM
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setSendFrom(Byte sendFrom) {
        this.sendFrom = sendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.IS_DELETED
     *
     * @return the value of tt_msg_log.IS_DELETED
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.IS_DELETED
     *
     * @param isDeleted the value for tt_msg_log.IS_DELETED
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.CREATED_BY
     *
     * @return the value of tt_msg_log.CREATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.CREATED_BY
     *
     * @param createdBy the value for tt_msg_log.CREATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.CREATED_TIME
     *
     * @return the value of tt_msg_log.CREATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.CREATED_TIME
     *
     * @param createdTime the value for tt_msg_log.CREATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.UPDATED_BY
     *
     * @return the value of tt_msg_log.UPDATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.UPDATED_BY
     *
     * @param updatedBy the value for tt_msg_log.UPDATED_BY
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.UPDATED_TIME
     *
     * @return the value of tt_msg_log.UPDATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.UPDATED_TIME
     *
     * @param updatedTime the value for tt_msg_log.UPDATED_TIME
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_msg_log.RECORD_VERSION
     *
     * @return the value of tt_msg_log.RECORD_VERSION
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_msg_log.RECORD_VERSION
     *
     * @param recordVersion the value for tt_msg_log.RECORD_VERSION
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }
}