package com.spring.cloud.interfaces.mapper;

import com.spring.cloud.domain.entity.MsgLog;
import com.spring.cloud.domain.entity.MsgLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    long countByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    int deleteByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    int insert(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    int insertSelective(MsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    List<MsgLog> selectByExample(MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") MsgLog record, @Param("example") MsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_msg_log
     *
     * @mbg.generated Fri Apr 26 14:23:40 GMT+08:00 2019
     */
    int updateByExample(@Param("record") MsgLog record, @Param("example") MsgLogExample example);
}